export const state = {
  _uiMode: null,
  currentSessionId: null,
  sessions: [],
  isStreaming: false,
  sessionTab: "personal",
  currentUser: null,
  llmConfigured: false,
  agentReady: false,
  currentReport: null,
  currentReportId: null,
  activeReportContexts: [],
  allReports: [],
  reportFilter: "all",
  currentJstackReport: null,
  currentJstackReportId: null,
  openGcReports: [],
  openJstackReports: [],
  gcHistoryReports: [],
  jstackHistoryReports: [],
  currentHeapdumpReport: null,
  currentHeapdumpReportId: null,
  openHeapdumpReports: [],
  heapdumpHistoryReports: [],
  analysisFeatures: ["gc", "jstack", "heapdump"],
};